services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: postech
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "2022:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S4f3P4ss -Q "SELECT 1"
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - postech-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postech-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=postech;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${JWT_KEY}
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - postech-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
      
volumes:
  sqlserver-data:
    driver: local

networks:
  postech-network:
    name: postech-network
    driver: bridge